# Generated by Django 5.2 on 2025-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialutilizado',
            old_name='cantidad_usada',
            new_name='cantidad_material',
        ),
        migrations.RemoveField(
            model_name='materialutilizado',
            name='tipo',
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='metros_disponibles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='unidades_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
