# Generated by Django 5.2 on 2025-05-26 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cantidad_usada_materialutilizado_cantidad_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpedido',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudpedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_proveedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
